In [2]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [ ]:
def An(theta, alpha, ai, di):
    return np.array([[np.cos(theta),-1*np.cos(theta)*np.sin(theta),np.sin(alpha)*np.sin(theta),ai*np.cos(theta)],
    [np.sin(theta),np.cos(theta)*np.cos(alpha),-1*np.sin(alpha)*np.cos(theta),ai*np.sin(theta)],
    [0,np.sin(alpha),np.cos(alpha),di],
    [0,0,0,1]]);


In [11]:
print(An(0,0,350,377))


[[  1.  -0.   0. 350.]
 [  0.   1.  -0.   0.]
 [  0.   0.   1. 377.]
 [  0.   0.   0.   1.]]


In [23]:
def A04(theta1, theta2, theta4, a1, a2, d1, d3, d4): 
    ux = np.cos(theta1 +theta2 - theta4);
    uy = np.sin(theta1 +theta2 - theta4);
    uz = 0;
    vx = np.sin(theta1 + theta2 - theta4);
    vy = -np.cos(theta1 + theta2 - theta4);
    vz = 0;
    wx = 0;
    wy = 0;
    wz = -1;
    qx = a1*np.cos(theta1)+a2*np.cos(theta1 +theta2);
    qy = a1*np.sin(theta1)+a2*np.sin(theta1 +theta2);
    qz = d1 -d3- d4;
    matrix = np.array([[ux,vx,wx,qx],[uy,vy,wy,qy],[uz,vz,wz,qz],[0,0,0,1]]);
    return matrix;
    

In [13]:
print(np.dot(np.dot(np.dot(An(0,0,350,377),An(0,np.pi,350,0)),An(0,0,0,0)),An(0,0,0,35)))

[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00  7.0000000e+02]
 [ 0.0000000e+00 -1.0000000e+00 -1.2246468e-16 -4.2862638e-15]
 [ 0.0000000e+00  1.2246468e-16 -1.0000000e+00  3.4200000e+02]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]


In [24]:
print(A04(0,0,0,350,350,377,0,35))

[[  1.   0.   0. 700.]
 [  0.  -1.   0.   0.]
 [  0.   0.  -1. 342.]
 [  0.   0.   0.   1.]]


# CINEMÁTICA DIRECTA

In [25]:
def A04SCARA(theta1, theta2, theta4, d4): 
    ux = np.cos(theta1 +theta2 - theta4);
    uy = np.sin(theta1 +theta2 - theta4);
    uz = 0;
    vx = np.sin(theta1 + theta2 - theta4);
    vy = -np.cos(theta1 + theta2 - theta4);
    vz = 0;
    wx = 0;
    wy = 0;
    wz = -1;
    qx = 350*np.cos(theta1)+350*np.cos(theta1 +theta2);
    qy = 350*np.sin(theta1)+350*np.sin(theta1 +theta2);
    qz = 377 -35- d4;
    matrix = np.array([[ux,vx,wx,qx],[uy,vy,wy,qy],[uz,vz,wz,qz],[0,0,0,1]]);
    return matrix;
    

q = (0, 0, 0, 0)

In [26]:
print(A04SCARA(0,0,0,0))

[[  1.   0.   0. 700.]
 [  0.  -1.   0.   0.]
 [  0.   0.  -1. 342.]
 [  0.   0.   0.   1.]]


In [31]:
print(A04SCARA(0,np.pi/2,0,0))

[[ 6.123234e-17  1.000000e+00  0.000000e+00  3.500000e+02]
 [ 1.000000e+00 -6.123234e-17  0.000000e+00  3.500000e+02]
 [ 0.000000e+00  0.000000e+00 -1.000000e+00  3.420000e+02]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]


In [32]:
print(A04SCARA(-np.pi/2,np.pi/2,0,400))

[[   1.    0.    0.  350.]
 [   0.   -1.    0. -350.]
 [   0.    0.   -1.  -58.]
 [   0.    0.    0.    1.]]


In [33]:
print(A04SCARA(np.pi,0,np.pi/2,200))

[[ 6.12323400e-17  1.00000000e+00  0.00000000e+00 -7.00000000e+02]
 [ 1.00000000e+00 -6.12323400e-17  0.00000000e+00  8.57252759e-14]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+00  1.42000000e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


# CINEMÁTICA INVERSA

In [ ]:
def A04Inversa(px, py, pz, phi)